### ISSUE TITLE
[BUG] Tech Reborn Elevator Block only going down.

### ISSUE THREAD

**Issue by Legion495** [AMPZNetwork/All-The-Fabric-5#2]
## Bug Description
The Elevator block of Tech Reborn does not go up.
The Block is used to move player vertically.

## Reproduction Steps
To replicate the problem, follow these steps:

1. Install https://modrinth.com/modpack/all-the-fabric-5/version/1.2
2. Test the Elevator Block
3. Power both blocks (creative solar panel or something)
4. Make sure they are on same coordinates other than vertical
5. Since limitations are unknown I would advice only 10-20 blocks apart
6. Shift to go down works
7. Jump to go up fails

Old Elevator Blocks used to work in this fashion.
Unless it is to be used in a different manner.
All this is on a self hosted server.

## Expected Outcome
Jump=Move one elevator block up

## Crash Log (if applicable)
No Crash

## Screenshots
Nothing to add

## Basic Information (please fill in the following details):
 - Operating System: Linux (Same deal on Windows)
 - All The Fabric 5 Version: v1.2
 - Platform: Modrinth
 - Additional Mods Installed: none

Further this Block is not listed on the Tech Reborn Wiki.
Is it supposed to be there?

**Comment by LabsZero** [comment]
Thank you for your report, I will see what i can do to fix this however it may be something that the mod dev will have to resolve .

**Comment by LabsZero** [comment]
I've found that there is a mod in the pack that is causing the issue, Looking into what one is the cause.

**Comment by rxay579** [comment]
If I may ask, what was the fix?

Having the same issue on a custom mod list and the AOF5 issue/changelog does not specify details.
The issue in the Tech Reborn issue tracker also does not specify.

**Comment by LabsZero** [comment]
> If I may ask, what was the fix?
> 
> Having the same issue on a custom mod list and the AOF5 issue/changelog does not specify details. The issue in the Tech Reborn issue tracker also does not specify.

The issue for ATFB5 was a mod called BackSlot having some conflict issue with Tech Reborn
